services:
  news-summarizer:
    build: .
    container_name: news-summarizer
    tty: true
    stdin_open: true
    ports:
      - "8501:8501"
    volumes:
      # Mount your local GGUF models directory
      - /Users/danildorofeev/.lmstudio/models/Qwen/Qwen3-1.7B-GGUF/:/app/data/models
      # - ${PWD}:/app # for debug
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
